import type { Series } from "./types";

const page = (seriesSlug: string, chapterSlug: string, pageNumber: number) => ({
  pageNumber,
  imageUrl: `/mock-pages/${seriesSlug}-${chapterSlug}-${pageNumber}.svg`,
  width: 900,
  height: 1280,
});

export const seriesSeed: Series[] = [
  {
    slug: "nighthawk-protocol",
    title: "Nighthawk Protocol",
    altTitles: ["Night Hawk", "Protocol Malam"],
    synopsis:
      "Kurir data bawah tanah nemu kunci enkripsi yang bisa membongkar guild korporat paling berbahaya di kota neon.",
    coverUrl: "/mock-covers/nighthawk.svg",
    type: "manhwa",
    status: "ongoing",
    contentRating: "teen",
    demographic: "seinen",
    authorName: "Raka Aster",
    artistName: "Mira Void",
    releaseYear: 2025,
    genres: ["Action", "Cyberpunk", "Mystery"],
    featured: true,
    updatedAt: "2026-05-29T10:00:00.000Z",
    chapters: [
      {
        slug: "chapter-003",
        numberLabel: "Chapter 3",
        numberSort: 3,
        title: "Packet Loss",
        publishedAt: "2026-05-29T10:00:00.000Z",
        pages: [1, 2, 3, 4].map((n) => page("nighthawk", "003", n)),
      },
      {
        slug: "chapter-002",
        numberLabel: "Chapter 2",
        numberSort: 2,
        title: "Blackbox Alley",
        publishedAt: "2026-05-22T10:00:00.000Z",
        pages: [1, 2, 3].map((n) => page("nighthawk", "002", n)),
      },
      {
        slug: "chapter-001",
        numberLabel: "Chapter 1",
        numberSort: 1,
        title: "Handshake",
        publishedAt: "2026-05-15T10:00:00.000Z",
        pages: [1, 2, 3].map((n) => page("nighthawk", "001", n)),
      },
    ],
  },
  {
    slug: "saltwater-oracle",
    title: "Saltwater Oracle",
    altTitles: ["Oracle Laut Asin"],
    synopsis:
      "Anak penjaga mercusuar bisa membaca masa depan lewat ombak, tapi tiap ramalan selalu minta tumbal ingatan.",
    coverUrl: "/mock-covers/saltwater.svg",
    type: "manga",
    status: "ongoing",
    contentRating: "teen",
    demographic: "shoujo",
    authorName: "Kei Maru",
    artistName: "Naya Tide",
    releaseYear: 2024,
    genres: ["Fantasy", "Drama", "Supernatural"],
    featured: true,
    updatedAt: "2026-05-28T08:00:00.000Z",
    chapters: [
      {
        slug: "chapter-012",
        numberLabel: "Chapter 12",
        numberSort: 12,
        title: "Low Tide Promise",
        publishedAt: "2026-05-28T08:00:00.000Z",
        pages: [1, 2, 3, 4].map((n) => page("saltwater", "012", n)),
      },
      {
        slug: "chapter-011",
        numberLabel: "Chapter 11",
        numberSort: 11,
        title: "The Bell Below",
        publishedAt: "2026-05-21T08:00:00.000Z",
        pages: [1, 2, 3].map((n) => page("saltwater", "011", n)),
      },
    ],
  },
  {
    slug: "iron-lantern-sect",
    title: "Iron Lantern Sect",
    altTitles: ["Tie Deng Men", "Sekte Lentera Besi"],
    synopsis:
      "Murid paling lemah dari sekte tua dapet lentera retak berisi teknik kultivasi yang dilarang seratus tahun lalu.",
    coverUrl: "/mock-covers/iron-lantern.svg",
    type: "manhua",
    status: "ongoing",
    contentRating: "teen",
    demographic: "shounen",
    authorName: "Han Qiu",
    artistName: "Lin Forge",
    releaseYear: 2023,
    genres: ["Cultivation", "Adventure", "Martial Arts"],
    updatedAt: "2026-05-26T09:30:00.000Z",
    chapters: [
      {
        slug: "chapter-041",
        numberLabel: "Chapter 41",
        numberSort: 41,
        title: "Ashes of the Outer Hall",
        publishedAt: "2026-05-26T09:30:00.000Z",
        pages: [1, 2, 3].map((n) => page("iron-lantern", "041", n)),
      },
      {
        slug: "chapter-040",
        numberLabel: "Chapter 40",
        numberSort: 40,
        title: "Nine Sparks Trial",
        publishedAt: "2026-05-19T09:30:00.000Z",
        pages: [1, 2, 3].map((n) => page("iron-lantern", "040", n)),
      },
    ],
  },
  {
    slug: "orbit-cafe-after-hours",
    title: "Orbit Cafe After Hours",
    altTitles: ["Kafe Orbit"],
    synopsis:
      "Slice of life tentang kafe kecil di stasiun luar angkasa yang tiap malam didatangi pelanggan dari timeline berbeda.",
    coverUrl: "/mock-covers/orbit-cafe.svg",
    type: "comic",
    status: "completed",
    contentRating: "all",
    demographic: "general",
    authorName: "Dina Pulse",
    artistName: "Sora Bean",
    releaseYear: 2022,
    genres: ["Slice of Life", "Sci-Fi", "Comedy"],
    updatedAt: "2026-05-20T11:00:00.000Z",
    chapters: [
      {
        slug: "chapter-024",
        numberLabel: "Chapter 24",
        numberSort: 24,
        title: "Last Order Before Dawn",
        publishedAt: "2026-05-20T11:00:00.000Z",
        pages: [1, 2, 3, 4].map((n) => page("orbit-cafe", "024", n)),
      },
      {
        slug: "chapter-023",
        numberLabel: "Chapter 23",
        numberSort: 23,
        title: "Meteor Foam",
        publishedAt: "2026-05-13T11:00:00.000Z",
        pages: [1, 2, 3].map((n) => page("orbit-cafe", "023", n)),
      },
    ],
  },
];
